### ISSUE TITLE
Tugas mendaftar ke GitHub dan fork repositori ini

### ISSUE THREAD

**Issue by dudung** [dudung/nt6094-01-2022-1#1]
1. Dengan email Gmail Anda [daftar ke GitHub](https://github.com/signup).
2. Gunakan akun tersebut untuk [login](https://github.com/login).
3. Untuk repositori ini (nt6094-01-2022-1) lakukan [fork](https://github.com/dudung/nt6094-01-2022-1/fork).
4. Cantumkan informasi nama pengguna Anda, NIM, dan for dari repositori ini sebagai komentar dari pesan ini. Sebagai contoh
  `user` [veedasch](https://github.com/veedasch)
  `fork` https://github.com/veedasch/nt6094-01-2022-1
6. Jawaban ditunggu sampai Kamis, 6 Oktober 2022, jam 1200. Dan dianggap sebagai salah satu tugas.

**Comment by Kapabihi** [comment]
Kapabihi 28721006
https://github.com/Kapabihi

**Comment by zakyrayadhi** [comment]
user [[zakyrayadhi]((https://github.com/zakyrayadhi)]
fork https://github.com/zakyrayadhi/nt6094-01-2022-1
NIM 28721001

**Comment by Kapabihi** [comment]
Kapabihi 28721006

user[[Kapabihi](((https://github.com/kapabihi)]
fork https://github.com/Kapabihi/nt6094-01-2022-1

**Comment by zen30621001** [comment]
Zen 30621001
user zen30621001
fork https://github.com/zen30621001/nt6094-01-2022-1

**Comment by indahoktav** [comment]
user indahoktav
fork https://github.com/indahoktav/nt6094-01-2022-1
NIM 30621008

**Comment by gitagenecya** [comment]
user gitagenecya
fork https://github.com/gitagenecya/nt6094-01-2022-1
NIM 28721003

**Comment by yuyunirmawati** [comment]
user yuyunirmawati
fork https://github.com/yuyunirmawati/nt6094-01-2022-1
NIM 38721002

**Comment by windanaw** [comment]
user windanaw
fork https://github.com/windanaw/nt6094-01-2022-1?organization=windanaw&organization=windanaw
NIM 30621004

**Comment by niningos** [comment]
user https://github.com/niningos
fork https://github.com/niningos/nt6094-01-2022-1
NIM 28721005

**Comment by niningos** [comment]
user [someone](https://github.com/niningos)

**Comment by niningos** [comment]
user [niningos](https://github.com/niningos)
fork https://github.com/niningos/nt6094-01-2022-1
NIM 28721005

**Comment by amaliashifa** [comment]
user amaliashifa
fork https://github.com/amaliashifa/nt6094-01-2022-1
NIM 20921007

**Comment by amaliashifa** [comment]
user amaliashifa
fork https://github.com/amaliashifa/nt6094-01-2022-1
NIM 20921007

**Comment by veedasch** [comment]
ss
